### PR TITLE
Update 2023-01-09-using-chat-gpt-in-codebase-stewardship.md

### PR DESCRIPTION
**Pull request by brandmuse**
Great piece. I did copy edit, changed some verbs and removed redundant phrases.

### CODE REVIEW

**Comment by Ainali** [comment]
Thanks! But should we really change the conversation? If so, perhaps we should remove the claim that this is the verbatim chat? (All the changes in my part of the conclusion are fine.)

**Comment by brandmuse** [comment]
No, I didn’t change anything. Just moved some verbs and other elements
around to read better as a printed text. I didn’t remove any content. If
you feel the changes altered the verbatim conversation, I totally agree
with you should you want to retain original texts.

**Comment by Ainali** [comment]
You also changed my prompt, right? Which means that if someone tries to replicate what we did, they will probably not get the same result and hence we look untrustworthy.

**Comment by brandmuse** [comment]
Hello, Jan,

My apologies, this is getting more complicated than I had intended. Is
there a way to go back to the original post and get it published as was. I
had seen other writers use Chat GTP and I thought it was a brilliant AI
device to get contents faster, but many folks also edit the content because
it would be put back into the AI system. In retrospect,  totally see where
you are coming from per the word VERBATIM, and I didn't intend to override
your thoughts. It was never intentional.

**Comment by Ainali** [comment]
@brandmuse  With the help of Eric, I managed to keep your edits to the surrounding text and restore the prompts and answers. Please review #409 to see if I got it right.

**Pull request merged**
