### PR TITLE
Add contributing file

### PR DESCRIPTION
**Pull request by Ainali**
Fixes #34

-----
[View rendered CONTRIBUTING.md](https://github.com/publiccodenet/blog/blob/contributing/CONTRIBUTING.md)
[View rendered README.md](https://github.com/publiccodenet/blog/blob/contributing/README.md)

### CODE REVIEW

**Review by ericherman — DISMISSED** [review]

**Comment by clausmullie** [comment]
@Ainali would it make sense to move the heading `How to create a blogpost on the Foundation’s blog` from the [blogging guide](https://about.publiccode.net/activities/communication/blogging.html) to the contributing file? and then link to the contributing file from the guide?

**Comment by Ainali** [comment]
> @Ainali would it make sense to move the heading `How to create a blogpost on the Foundation’s blog` from the [blogging guide](https://about.publiccode.net/activities/communication/blogging.html) to the contributing file? and then link to the contributing file from the guide?

In a sense it would, but I'm not sure how that would fit with our ambitions to have About being our canonical place of information of our activities.

**Comment by clausmullie** [comment]
Yes, that is a valid consideration. But on the other hand - it is basically an instruction for how to make a pull request on this repository, so something one could expect to be in the contributing.md.

**Review by clausmullie — APPROVED** [review]
I'd be happy to merge as is - @Ainali are you happy with the changes I made to your original text?

**Pull request merged**
